import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script defer src="https://umami.jdapps.online/script.js" data-website-id="d6703312-a416-496d-b1cf-f47697bdfe83"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
